---
language: ruby

cache: bundler

before_install:
  - rm Gemfile.lock || true
  - gem --version
  - bundle -v

sudo: false

script: 'bundle exec rake validate lint spec'

matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 3"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4"
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5"
    before_install:
      - bundle -v
      - rm Gemfile.lock || true
      - gem update --system --no-doc
      - gem update bundler --no-doc
      - gem --version
      - bundle -v
  - rvm: 2.5.1
    env: PUPPET_GEM_VERSION="~> 6"
    before_install:
      - bundle -v
      - rm Gemfile.lock || true
      - gem update --system --no-doc
      - gem update bundler --no-doc
      - gem --version
      - bundle -v

notifications:
  email: false
